---
title:"PubPol 779: Applied Econometrics" # add course title here 
format:
 html: default
---



Instructor: Jonathan Hanson (he/him)\
jkhanson\@umich.edu\
4223 Weill Hall, 734-615-1496\
Office Hours: Mon. 3:00--4:30, Fri. 11:00--12:00, or by appointment\

The objective of this course is to help gain students proficiency in
advanced techniques that are employed in the service of causal
inference, including selection models, regression discontinuity,
difference-in-differences, matching methods, and interrupted time
series. Students will understand how to design, execute, and interpret
the results from estimation techniques beyond the standard OLS model.
Students will learn to work with data structures in which the
observations are not independently and identically distributed:
time-series data, panel data, time-series-cross-sectional data,
multi-level data, etc.

Prerequisite: it is assumed that students in this course will have
previously taken Public Policy 529 and Public Policy 639, or equivalent
coursework. Students are advised to consult with the instructor if they
received a grade lower than A- in either of these courses.

## Class Meeting Schedule

Unless otherwise noted, lectures are Mondays and Wednesdays from
10:00--11:20 pm in 1210 Weill Hall.

## Textbooks There is no single textbook for this course, and
readings will be available on the Canvas website. You can log into
Canvas at <http://canvas.umich.edu>. The following books and articles,
however, will be good references for course material. The Cunningham and
Huntington-Klein texts are available in an online format.

- Alberto Abadie and Matias D. Cattaneo. 2018. "Econometric Methods for
  Program Evaluation." *Annual Review of Economics* 10: 465--503.
  [Link](https://economics.mit.edu/sites/default/files/publications/ARE-typo-Fig4-corrected.pdf).

- Joshua D. Angrist and Jörn-Steffen Pischke. 2015. *Mastering 'Metrics:
  The Path from Cause to Effect*. Princeton: Princeton University Press.

- Scott Cunningham. 2021. *Causal Inference: The Mixtape*. New Haven:
  Yale University Press. [Link](https://mixtape.scunning.com).

- Paul J. Gertier, Sebastian Martinez, Patrick Premand, Laura B.
  Rawlings, and Christel M. J. Vermeersch. 2016. *Impact Evaluation in
  Practice*, 2nd ed. Washington, DC: World Bank.
  [Link](https://search.lib.umich.edu/catalog/record/99187424055806381).

- Nick Huntington-Klein. 2021. *The Effect: An Introduction to Research
  Design and Causality.* Chapman & Hall.
  [Link](https://www.theeffectbook.net/index.html).

- J. Scott Long. 1997. *Regression Models for Categorical and Limited
  Dependent Variables*. Sage Publications.

## Assignments and Grading

Your grade for this course will be determined by the following:

  Course Component    \% of grade
  ------------------ -------------
  Problem sets            50%
  Midterm exam            25%
  Final exam              25%

There will be six major problem sets in this course. Additionally, there
will be two exams -- one midterm and one final -- covering the
first-half and second halves of the course respectively. These will be
take-home exams, and you will have approximately one week to work on
them.

You are encouraged to help each other figure out the answers to the
problem sets, but it is expected that you write up your answers
independently. The take-home exams are exams. For these exams, you are
not permitted to communicate with any person other than the course
instructor. Receiving help from any other person, or providing help to
any other person, is a violation of academic integrity and will result
in significant consequences. Use of generative AI tools to answer exam
questions is also an academic integrity violation. You may, however,
consult any textbook or static internet-resources.

:::: center
::: {##default}
  Assignment                       Due Date
  -------------------------------- --------------
  Problem Set 1                    September 15
  Problem Set 2                    September 24
  Problem Set 3                    October 6
  Take-home Midterm Exam           October 20
  Problem Set 4                    November 3
  Problem Set 5                    November 17
  Problem Set 6                    December 8
  Final Exam (take-home portion)   December 17

  : Assignment and Exam Calendar
:::
::::


::: center
**Advanced Estimation Methods for Cross-Sectional Data**
:::

## August 25: Principles of Maximum Likelihood Estimation In
the classical linear regression model and its variants, we find the
parameters of interest (i.e. the regression coefficients) though
analytic formulas. With Maximum Likelihood Estimation (MLE), these
parameters are often found by a search algorithm which tours the
parameter space and finds the values of the parameters that are "most
likely" given the data. The power of MLE its flexibility. Many different
functional forms are possible, facilitating analysis of many kinds of
data for which linear regression is not suitable.

- M S Sasidhar. 2018. "Introduction to Maximum Likelihood Estimation."
  <https://tinyurl.com/y2hb45vv>

- Sherry Towers. "Maximum Likelihood Estimation."
  <http://www.sherrytowers.com/mle_introduction.pdf>.

- Online simulation by Shawna Metzger:
  <https://mybinder.org/v2/gh/MetzgerSK/shinyElement/major?urlpath=shiny/mleLogit/>.

## August 27 & September 3: Dichotomous Dependent Variables

When our dependent variables are dichotomous, OLS might be problematic.
For one thing, OLS can in some cases produce predicted values of the
dependent variable that fall outside the range the 0-1 range. Other
problems arise with non-normality of disturbances and non-linear effects
of independent variables. With Maximum Likelihood Estimation, we can use
functional forms that are designed for these data: probit and logit
models.

- J. Scott Long. 1997. "Binary Outcomes: The Linear Probability, Probit,
  and Logit Models" In *Regression Models for Categorical and Limited
  Dependent Variables*, chapter 3.

- Robin Gomila. 2020. "Logistic or Linear? Estimating Causal Effects of
  Experimental Treatments on Binary Outcomes Using Regression Analysis."
  *Journal of Experimental Psychology: General* 150(4): 700--709.

- Sheheryar Banuri, Stefan Dercon, and Varun Gauri. 2019. "Biased Policy
  Professionals." *The World Bank Economic Review* 33(2): 310--327.

- Edward C. Norton, Bryan E. Dowd, Melissa M. Garrido, and Matthew
  L. Maciejewski. 2024. "Commentary: Requiem for odds ratios." *Health
  Services Research* 59:e14337.

- Kai Arzheimer. May 13, 2025. "ME at the Margins: Average Marginal
  Effects, Marginal Effects at the Mean, and Stata's margins command."
  [Blog
  posting](https://www.kai-arzheimer.com/me-at-the-margins-average-marginal-effects-marginal-effects-at-the-mean-and-statas-margins-command/).

## September 9: Ordinal Categories as Dependent Variables

When the dependent variable consists of ordinal categories, the list of
possible problems grows. We can use ordered probit and ordered logit
models for this kind data. A key objective is to learn how to interpret
and convey the results.

- J. Scott Long. 1997. "Ordinal Outcomes: Ordered Logit and Ordered
  Probit Analysis." In *Regression Models for Categorical and Limited
  Dependent Variables*, chapter 5.

- Zijing Lin and Wei "David" Fan. 2020. "Bicycle Ridership Using
  Crowdsourced Data: Ordered Probit Model Approach." *Journal of
  Transportation Engineering, Part A: Systems* 146(8): 1--15.

## September 10: Nominal Categories as Dependent Variables

With unordered categories, estimation becomes trickier since we cannot
use a latent dimension as an underlying framework. We can use
multinomial logit models in these circumstances.

- J. Scott Long. 1997. "Nominal Outcomes: Multinomial Logit and Related
  Models." In *Regression Models for Categorical and Limited Dependent
  Variables*, chapter 6.

- M. Niaz Asadullah. 2018. "Madrasah for Girls and Private School for
  Boys? The Determinants of School Type Choice in Rural and Urban
  Indonesia." *International Journal of Educational Development* 62:
  96--111.

## September 15 & 17: Count Models

Count models are for cases in which the dependent variable is a count of
the number of times something occurs.

- Will Koehrsen. 2019. "The Poisson Distribution and Poisson Process
  Explained." [Blog
  posting](https://builtin.com/data-science/poisson-process#). Updated
  by Brennan Whitfield, July 28, 2023.

- Stefany Coxe, Stephen G. West, and Leona S. Aiken. 2009. "The Analysis
  of Count Data: A Gentle Introduction to Poisson Regression and Its
  Alternatives." *Journal of Personality Assessment* 91(2): 121--136.

- Rainer Winkelmann (2015). "Counting on Count Data Models." IZA World
  of Labor 2015: 148.

- Paul Kwame Nkegbe and Naasengnibe Kuunibe. 2019. "Poverty and Malaria
  Morbidity: A Study Using Count Regression Model." SAGE Research
  Methods Cases in Business and Management.

:::: samepage
::: center
**Causal Inference for Cross-Sectional Data**
:::

## September 22 & 24: Sample Selection and Related Models

The purpose of selection models is to address situations in which the
cases that make it into the sample are different in important,
unmeasured ways from those who do not, and these unmeasured factors are
relevant for predicting the dependent variable. In other situations,
assignment into the treatment condition is non-random and correlated
with relevant, unmeasured factors.
::::

- Shenyang Guo and Mark W. Fraser. 2014. *Propensity Score Analysis*,
  chapter 4. Sage Publications, Inc. Note: the Stata "treatreg" command
  described here is called "etregress" in newer versions of Stata.

- Claire Infante-Rivard and Alexandre Cusson. 2018. "Reflection on
  Modern Methods: Selection Bias -- A Review of Recent Developments."
  *International Journal of Epidemiology* 47(5): 1714--1722.

- Shawn Bushway, Brian D. Johnson, and Lee Ann Slocum. 2007. "Is the
  Magic Still There? The Use of the Heckman Two-Step Correction for
  Selection Bias in Criminology." *Journal of Quantitative Criminology*
  23: 151--178.

- Manh Hung Do and Sang Chul Park. 2019. "Impacts of Vietnam's New Rural
  Development Policy on Rural Households' Income: Empirical Evidence
  from the Heckman Selection Model." *International Review of Public
  Administration* 24(4): 229--245.

- Marijana Andrijić and Tajana Barbić. 2018. "Trick or Treat? The Effect
  of IMF Programmes on Mobilising FDI in CESEE Countries." *Czech
  Journal of Economics and Finance* 68(3): 245--266.

## September 29 & 1: Multivariate Matching Methods

With observational data, we face inherent challenges in estimating the
average treatment effect (ATE) of some policy intervention because the
treatment is not randomly-assigned. The treatment group and control
group may differ from each other, in the aggregate, on both observable
and unobservable characteristics in ways other than the treatment, and
we cannot adequately control for these other factors. Matching methods
are intended to bring balance to the treatment groups on these other
characteristics to reduce bias in estimating the ATE. In this section of
the course we will learn various matching methods and develop awareness
of their limitations.

- Scott Cunningham. 2021. "Matching and Subclassification." In *Causal
  Inference: The Mixtape*, chapter 5. Yale University Press. [Link to
  online
  version](https://mixtape.scunning.com/05-matching_and_subclassification).

- C. Lockwood Reynolds and Stephen DesJardins. 2009. "The Use of
  Matching Methods in Higher Education Research." In *Higher Education:
  Handbook of Theory and Research*, ed. John C. Smart. Springer.

- Elizabeth Stuart. 2010. "Matching Methods for Causal Inference: A
  Review and a Look Forward." *Statistical Science* 25(1): 1--21.

- Jonathan Bartlett. 2016. "Why You Shouldn't Use Propensity Score
  Matching." [The Stats Geek
  blog](https://thestatsgeek.com/2016/09/07/why-you-shouldnt-use-propensity-score-matching/).

- Alexander Pfaff, Juan Robalino, Eirivelthon Lima, Catalina Sandoval,
  and Luis Diego Herrera. 2014. "Governance, Location, and Avoided
  Deforestation from Protected Areas: Greater Restrictions Can Have
  Lower Impact, Due to Differences in Location." *World Development* 55:
  7--20.

## October 6 & 8: Regression Discontinuity Models

Regression discontinuity models are useful for scenarios in which
assignment into the treatment group is based upon a cutoff score on some
observable characteristic or a particular date of implementation. In
short, the difference between the predicted outcomes on either side of
the cutoff point becomes a way to estimate the size of the treatment
effect. This section of the course explores various uses of these
models.

- Nick Huntington-Klein. 2022. "Regression Discontinuity." In *The
  Effect: An Introduction to Research Design and Causality*, chapter 20.
  Routledge. [Link to online
  version](https://www.theeffectbook.net/ch-RegressionDiscontinuity.html).

- Matias D. Cattaneo, Rocı́o Titiunik, and Gonzalo Vazquez-Bare. 2020.
  "The Regression Discontinuity Design." *Handbook of Research Methods
  in Political Science and International Relations*, chapter 44. Sage
  Publications.

- Pei Zhu. 2019. "Using a Regression Discontinuity Design for Evaluation
  Studies." MDRC.

- David S. Lee. 2008. "Randomized Experiments from Non-Random Selection
  in U.S. House Elections." *Journal of Econometrics* 142: 675--697.

- Analisa Packham and Brittany Street. 2018. "The Effects of Physical
  Education on Student Fitness, Achievement, and Behavior." Manuscript.

## October 13: Fall Study Break

## October 15: Instrumental Variables Analysis Oftentimes,
there is strong reason to believe that the relationship between our
dependent variable, and one or more of our independent variables, is
endogenous. In such cases, our estimate of the coefficient on the
independent variable will be biased. If we can find a third variable,
however, which only has an effect on the dependent variable through the
endogenous independent variable, we can identify the correct
relationship.

- Nick Huntington-Klein. 2022. "Instrumental Variables." In *The Effect:
  An Introduction to Research Design and Causality*, chapter 19.
  Routledge. [Link to online
  version](https://theeffectbook.net/ch-InstrumentalVariables.html).

- Allison J. Sovey and Donald P. Green. 2011. "Instrumental Variables
  Estimation in Political Science: A Readers' Guide." *American Journal
  of Political Science* 55(1): 188--200.

- Paul J. Gertler, Sebastian Martinez, Patrick Premand, Laura B.
  Rawlings, and Christel M. J. Vermeersch. 2016. "Instrumental
  Variables: Evaluating Programs When Not Everyone Complies with Their
  Assignment." In *Impact Evaluation in Practice*, 2nd edition. World
  Bank Publications.

- Blog Post. 2015. "Friends Don't Let Friends Do IV."
  <https://tinyurl.com/y5ee3j86>.

::: center
**Estimation Methods for Time-Series and Panel Data**
:::

## October 20 & 22: Regression with Time-Series Data The
standard assumption is that our data are independent and identically
distributed. When we have time-series data, such as the results of
monthly polls on presidential approval or some other case of repeated
observations of the same object, this assumption is violated. The
stochastic component of one observation may be correlated with the one
preceding it and the one that follows. We spend about two sessions on
this topic.

- Aptech Data Analytics Blog. 2020. "Introduction to the Fundamentals of
  Time Series Data and Analysis." <https://tinyurl.com/vzud6yj>.

- Jon C. Pevehouse and Jason D. Brozek. 2008. "Time-Series Analysis." In
  *The Oxford Handbook of Political Methodology*, chapter 19.

- Janet M. Box-Steffensmeier, John R. Freeman, Matthew P. Hitt, and
  Jon C. W. Pevehouse. 2014. "Dynamic Regression Models." In *Time
  Series Analysis for the Social Sciences*, chap. 3. Cambridge
  University Press.

- Andrew Q. Phillips. 2021. "How to avoid incorrect inferences (while
  gaining correct ones) in dynamic models." *Political Science Research
  and Methods*, First View, 1--11. DOI:
  <https://doi.org/10.1017/psrm.2021.31>.

## October 27: Multi-Level Models

When our data consist of individual cases that are embedded within
higher-level units -- such as school children inside classrooms, which
are inside schools -- we need methods that can estimate both individual
and unit-level effects. In this section of the course, we explore the
use of multi-level models for this purpose.

- Ana V. Diez-Roux. 2000. "Multilevel Analysis in Public Health
  Research." *Annual Review of Public Health* 21: 171--192.

- Michael Freeman. "An Introduction to Hierarchical Modeling."
  Visualization available at <http://mfviz.com/hierarchical-models/>.

- Use chapter from Multilevel Modeling in Plain Language book from
  bookshelf.

- Tim Smith and Gerald Shively. 2019. "Multilevel analysis of
  individual, household, and community factors influencing child growth
  in Nepal." *BMC Pediatrics* 19(91): 1--14.

## October 29 and November 3 & 5: Regression with Panel Data We
have a panel when our data contain repeated observations of a sample of
objects, such as a set of individuals who are surveyed periodically or a
time series of cross-national data. In this scenario, we need to think
about the non-independence of our observations both across time and
space.

- Aptech Data Analytics Blog. 2020. "Introduction to the Fundamentals of
  Panel Data." <https://tinyurl.com/y4gt52db>. (short intro)

- Tae Ho Eom, Sock Hwan Lee, and Hua Xu. 2007. "Introduction to Panel
  Data Analysis. Concepts and Practices." In *Handbook of Research
  Methods in Public Administration*, Gerald R. Miller and Kaifeng Yang,
  eds. CRC Press.

- Robert Kubinec. 2020. "What Panel Data is Really All About."
  <http://www.robertkubinec.com/post/fixed_effects/>.

- Matthias Collischon and Andreas Eberl. 2020. "Let's Talk About Fixed
  Effects: Let's Talk About All the Good Things and the Bad Things."
  *Köln Z Soziol* 72: 289--299.

- Nathaniel Beck and Jonathan N. Katz. 2011. "Modeling Dynamics in
  Time-Series-Cross-Section Political Economy Data." *Annual Review of
  Political Science* 14: 331--52.

- Hanson, Jonathan K. 2015. "Democracy and State Capacity: Complements
  or Substitutes?" *Studies in Comparative International Development*
  50: 304-330.

::: center
**Causal Inference for Time-Series and Panel Data**
:::

## November 10, 12, 17 & 19: Difference-in-Differences Models

Difference-in-difference models are useful when: 1) we have observations
of each of the members of the sample for at least two periods in time;
and, 2) one group within the sample experienced the treatment during the
time frame under study, while the other did not. We thus can observe
whether group-level differences in the outcome of interest changed from
one period to the next, facilitating an estimate of the treatment
effect.

*General overviews*

- Dmitry Arkhangelsky and Guido Imbens. 2024. "Causal models for
  longitudinal and panel data: a survey." *Econometrics Journal* 27:
  C1--C61. This is a thorough review. Very good but more challenging
  read.

- Yiqing Xu. 2023. "Causal Inference with Time-Series Cross-Sectional
  Data: A Reflection." In *The Oxford Handbook of Engaged Methodological
  Pluralism in Political Science*, Box-Steffensmeier et al., eds. Oxford
  University Press. Another overview that is a bit more accessible.

*Basic DiD models*

- Scott Cunningham. 2021. "Difference-in-Differences." *Causal
  Inference: The Mixtape*, chapter 9.
  <https://mixtape.scunning.com/09-difference_in_differences>.

- Clément de Chaisemartin and Xavier D'Haultfœuille. June 2025.
  *Credible Answers to Hard Questions: Differences-in-Differences for
  Natural Experiments*. [Textbook in
  progress](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4487202).

- Apoorva Lal. 2025. "When can we get away with using the two-way fixed
  effects regression?" Manuscript.

*Recent approaches/innovations*

- Guangyi Wang, Rita Hamad, and Justin S. White. 2024. "Advances in
  Differences-in-differences Methods for Policy Evaluation Research."
  *Epidemiology* 35(5): 628--637.

- Jonathan Roth, Pedro H. C. Sant'Anna, Alyssa Bilinski, and John
  Poe. 2023. "What's Trending in Difference-in-Differences? A Synthesis
  of the Recent Econometrics Literature." *Journal of Econometrics* 235:
  2218--2244. This is an overview.

- Brantly Callaway and Pedro H.C. Sant'Anna. 2021.
  "Difference-in-Differences with Multiple Time Periods." *Journal of
  Econometrics* 225: 200--230.

- Liyang Sun and Sarah Abraham. 2021. "Estimating Dynamic Treatment
  Effects in Event Studies with Heterogeneous Treatment Effects."
  *Journal of Econometrics*, 225: 175--199.

- Arindrajit Dube, Daniele Giradi, Òscar Jordà, and Alan M.
  Taylor. 2025. "A Local Projections Approach to
  Difference-in-Differences." *Journal of Applied Econometrics*,
  0:1--18.

- Licheng Liu, Ye Wang, and Yiqing Xu. 2022. "A Practical Guide to
  Counterfactual Estimators for Causal Inference with Time-Series
  Cross-Sectional Data." *American Journal of Political Science*.

- Amanda Weiss. 2024. "How Much Should We Trust Modern
  Difference-in-Differences Estimates?" Working Paper.

*Examples from the literature and tutorials*

- Janet Currie and Reed Walker. 2011. "Traffic Congestion and Infant
  Health: Evidence from E-ZPass." *American Economic Journal: Applied
  Economics* 3(1): 65-90.

- Andrew Goodman-Bacon. 2018. "Public Insurance and Mortality: Evidence
  from Medicaid Implementation." *Journal of Political Economy* 126(1):
  216--262.

- Ziyi Liu and Yiqing Xu. 2025. "New DID Methods," chapter 5, *fect -
  User Manual*. <https://yiqingxu.org/packages/fect/05-panel.html>. This
  is a very helpful guided implementation of various DiD estimation
  methods using R.

## November 24 & December 1: Interrupted Time Series With
cross-sectional data, we used regression discontinuity models to make a
causal inference around a cutoff point on an observable characteristic.
With time-series data, that cutoff point can be a point in time, such as
the date of a policy implementation. Comparison cases facilitate the
identification of shifts in levels and trends of the outcome variable.

- Youseop Shin. 2017. "Time Series Analysis as an Impact Analysis
  Method." In *Time Series Analysis in the Social Sciences: The
  Fundamentals*, chap. 7. University of California Press.

- Kelly Hallberg, Ryan Williams, Andrew Swanlund, and Jared Eno. 2018.
  "Short Comparative Interrupted Time Series using Aggregate
  School-level Data in Education Research." *Educational Researcher*
  47(5): 295--306.

- Catherine Hausman and David S. Rapson. 2018. "Regression Discontinuity
  in Time: Considerations for Empirical Applications." *Annual Review of
  Resource Economics* 10(21): 1--20.

- Kosuke Imai, In Song Kim, and Erik H. Wang. 2021. "Matching Methods
  for Causal Inference with Time-Series Cross Sectional Data." *American
  Journal of Political Science*, Published Online.

- Hinda Ruton et al. 2018. "The Impact of an mHealth Monitoring System
  on Health Care Utilization by Mothers and Children: An Evaluation
  Using Routine Health Information in Rwanda." *Health Policy and
  Planning* 33: 920--927.

- David K. Humphreys, Antonio Gasparrini, and Douglas J. Wiebe. 2017.
  "Evaluating the Impact of Florida's 'Stand Your Ground' Self-defense
  Law on Homicide and Suicide by Firearm: An Interrupted Time Series
  Study." *JAMA Internal Medicine* 177(1): 44--50.

## December 3 & 8: Synthetic Control Method

This method builds upon matching methods by creating a "synthetic"
comparison case out of a pool of possible cases. Ideally, we would be
able to compare a case that has undergone some treatment to the
counterfactual scenario in which it had not undergone the treatment.
Since this counterfactual scenario does not exist, we construct one
using a weighted average of similar cases that did not undergo the
treatment. We then can compare the observed outcomes against those
predicted by under the counterfactual.

- Alberto Abadie. 2021. "Using Synthetic Controls: Feasibility, Data
  Requirements, and Methodological Aspects." *Journal of Economic
  Literature* 59(2): 391-425.

- Robert McClelland and Livia Mucciolo. 2022. "An Update on the
  Synthetic Control Method as a Tool to Understand State Policy." Tax
  Policy Center. Urban Institute & Brookings Institution.

- John Springford. 2018. "The Cost of Brexit to June 2018." Center for
  European Reform Insight, September 30, 2018.

- Thales A. P. West, Sven Wunder, Erin O. Sills, Jan Börner, Sami W.
  Rifai, Alexandra N. Neidermeier, Gabriel P. Frey, and Andreas Kontole.
  "Action needed to make carbon offsets from forest conservation work
  for climate change mitigation." *Science* 381(6660): 873--877.

- Yuan-Ying Chi, Yuan-Yuan Wang, and Jin-Hua Xu. 2021. "Estimating the
  impact of the license plate quota policy for ICEVs on new energy
  vehicle adoption by using synthetic control method." *Energy Policy*
  149: 1--13.

## Take-home Final Exam due by Monday, December 17
